# Jekyll configuration

name: milliscents-com
description: Amelia Causer's milliscents website
author:
  name: Mike Causer
  email: mcauser@gmail.com

url: http://milliscents.github.io/milliscents-com

exclude: [".ruby-version", "Gemfile", "Gemfile.lock", "README.md"]

sass:
  style: compressed

encoding: utf-8
